# Copyright 2021 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

licenses(["notice"])

exports_files([
    "ca.pem",
    "revoked.key",
    "revoked.pem",
    "valid.key",
    "valid.pem",
    "ab06acdd.r0",
    "ab06acdd.r1",
    "ab06acdd.r2",
    "ab06acdd.r3",
    "ab06acdd.r4",
    "ab06acdd.r5",
    "ab06acdd.r6",
    "ab06acdd.r7",
    "ab06acdd.r8",
    "ab06acdd.r9",
    "ab06acdd.r10",
])
